from collections.abc import Iterator
from contextlib import contextmanager

import psycopg
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool

from . import config

SCHEMA = """
CREATE TABLE IF NOT EXISTS entries (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT    NOT NULL,
    content         TEXT    NOT NULL,

    pin_hash        TEXT    NOT NULL,
    edit_token      TEXT    NOT NULL,
    failed_attempts INTEGER NOT NULL DEFAULT 0,
    locked_until    TIMESTAMPTZ,

    is_secret       BOOLEAN NOT NULL DEFAULT FALSE,
    photo           TEXT,
    owner_reply     TEXT,
    owner_reply_at  TIMESTAMPTZ,

    ip_hash         TEXT,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ,
    deleted_at      TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_entries_feed ON entries (deleted_at, id DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_entries_token ON entries (edit_token);

-- 사진 바이트는 entries에 두지 않는다. 피드 질의가 SELECT *라서 컬럼으로 두면
-- 목록을 열 때마다 모든 사진을 딸려 읽는다.
CREATE TABLE IF NOT EXISTS photos (
    name TEXT PRIMARY KEY,
    data BYTEA NOT NULL
);
"""

# WEBP는 이미 압축되어 있다. TOAST가 다시 압축을 시도해봐야 얻는 게 없다.
PHOTO_STORAGE = "ALTER TABLE photos ALTER COLUMN data SET STORAGE EXTERNAL"

# SQLite 시절에는 시각을 ISO 문자열 TEXT로 두었고, Postgres로 옮기면서 그대로
# 딸려 왔다. CREATE TABLE IF NOT EXISTS는 이미 있는 테이블을 고치지 않으므로
# 살아 있는 DB는 여기서 바꾼다. 아직 TEXT인 컬럼만 골라 바꾸니 몇 번 돌아도 같다.
# 기존 값은 전부 ISO 8601이라 ::timestamptz로 바로 읽힌다.
TIME_COLUMNS = ("locked_until", "owner_reply_at", "created_at", "updated_at", "deleted_at")
TEXT_TO_TIMESTAMPTZ = """
DO $$
DECLARE
    col text;
BEGIN
    FOREACH col IN ARRAY ARRAY[{columns}] LOOP
        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'entries'
              AND column_name = col
              AND data_type = 'text'
        ) THEN
            EXECUTE format(
                'ALTER TABLE entries ALTER COLUMN %I TYPE timestamptz USING %I::timestamptz',
                col, col
            );
        END IF;
    END LOOP;
END $$
""".format(columns=", ".join(f"'{c}'" for c in TIME_COLUMNS))

_pool: ConnectionPool | None = None


def pool() -> ConnectionPool:
    """첫 요청에서 만든다. import 시점에 붙으면 DB 없이는 테스트 수집조차 안 된다."""
    global _pool
    if _pool is None:
        _pool = ConnectionPool(
            config.DATABASE_URL,
            # min_size=0이라 idle instance는 connection을 붙들지 않는다. Cloud Run이
            # scale to zero 하는 것과 짝이 맞는다.
            min_size=0,
            max_size=4,
            # autocommit이 아니면 psycopg가 transaction을 열고, 이 코드는 아무 데서도
            # commit하지 않으므로 pool에 반납될 때 전부 rollback된다. sqlite3에
            # isolation_level=None을 주던 것과 같은 자리다.
            kwargs={"autocommit": True, "row_factory": dict_row},
            # 내주기 전에 연결이 살아 있는지 확인하고, 죽었으면 조용히 새로 만든다.
            #
            # 없으면 idle 뒤 첫 요청이 500으로 떨어진다. Cloud Run은 instance가
            # idle하면 CPU를 얼려서 pool의 정리 작업이 안 돌고, 그동안 Neon
            # pooler는 idle 연결을 끊는다. 깨어나면 pool은 이미 끊긴 연결을
            # 멀쩡한 줄 알고 들고 있다.
            #
            # 요청마다 왕복이 한 번 늘지만 같은 region이라 1~3ms다.
            check=ConnectionPool.check_connection,
            open=True,
        )
    return _pool


@contextmanager
def cursor() -> Iterator[psycopg.Connection]:
    with pool().connection() as conn:
        yield conn


def init() -> None:
    """cold start마다 돈다. instance 여러 개가 동시에 떠도 안전해야 한다.

    CREATE TABLE IF NOT EXISTS는 생각만큼 안전하지 않다. 두 connection이 같은
    순간에 실행하면 하나가 pg_type unique violation으로 터진다. advisory lock으로
    한 번에 하나만 들어가게 막는다.
    """
    with cursor() as conn, conn.transaction():
        conn.execute("SELECT pg_advisory_xact_lock(hashtext('guestbook-schema'))")
        conn.execute(SCHEMA)
        conn.execute(PHOTO_STORAGE)
        conn.execute(TEXT_TO_TIMESTAMPTZ)


def close() -> None:
    global _pool
    if _pool is not None:
        _pool.close()
        _pool = None
